services:
  postgres:
    container_name: postgres-db
    image: postgres:16.0
    environment:
      POSTGRES_DB: postgres-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped

  redis:
    container_name: redis-cache
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - db
    restart: unless-stopped
    command: redis-server --appendonly yes

  vault:
    container_name: vault-server
    image: hashicorp/vault:1.15
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    networks:
      - db
    command: server -dev
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    restart: unless-stopped
#unseal key :     84AHRMB7LUK+x+j1XXMH5jzBobhD5+Pizse8h3bQOns=
#health : http://localhost:8200/v1/sys/health

# actuator:
#  http://localhost:9090/actuator/metrics/hikaricp.connections.active
#  http://localhost:9090/actuator/metrics/hikaricp.connections.idle


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3030:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    networks:
      - monitoring


networks:
  db:
    driver: bridge
  monitoring:
    driver: bridge

volumes:
  db:
  redis_data:
  prometheus_data:
  grafana_data:
