server:
  port: 9090

spring:
  application:
    name: authServer
  #  Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres-db
    password: admin
    username: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/oauth2/jwks
      authorization-server:
        issuer-uri: http://localhost:9090

  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      #      password:
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

# SMS Configuration (Twilio)
sms:
  otp:
    expiration-minutes: 5
    rate-limit-minutes: 1

logging:
  level:
    root: info
    web: debug
    org:
      springframework:
        security: debug

#Swagger Configuration
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  show-actuator: true
  api-docs:
    enabled: true
    path: /v3/api-docs

#Bunlde Configuration
config:
  language: fa